### ISSUE TITLE
Model House

### ISSUE THREAD

**Issue by jr22741** [jr22741/SpookySealTeam7-GameJam#2]
Model House

**Comment by dw22682** [comment]
plan: 
- create a map of the house
- then create a model in blender or something?
- then add furniture?

**Comment by dw22682** [comment]
![Image](https://github.com/user-attachments/assets/154b7751-8d21-40b3-89fa-2daea5ddb532)

**Comment by dw22682** [comment]
house is exported to obj file and then added to assets folder

a sample scene has also been created
